//! Pastes by writing the pasteboard and posting ⌘V, then puts the previous
//! pasteboard contents back if nobody changed it in the meantime.

use std::time::Duration;

use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardTypeString, NSPasteboardWriting};
use objc2_foundation::{NSArray, NSData, NSString};
use tauri::{AppHandle, Runtime};

use super::ffi::*;

/// Marks events we post so our own key hook lets them through ("Moli").
pub const INJECTED: i64 = 0x4D6F_6C69;
const KEY_V: u16 = 9;
/// Let the target app read the pasteboard before restoring it.
const RESTORE_AFTER: Duration = Duration::from_millis(600);
/// Clipboard managers skip items with these types (nspasteboard.org).
const MARKER_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

/// Every item's data for every type, copied out so it can cross threads.
type Snapshot = Vec<Vec<(String, Vec<u8>)>>;

pub async fn paste<R: Runtime>(
    app: &AppHandle<R>,
    text: String,
    restore: bool,
) -> Result<(), String> {
    let trusted = unsafe { AXIsProcessTrusted() };
    // Without Accessibility the ⌘V goes nowhere, so leave the text on the
    // clipboard for the user to paste by hand.
    let restore = restore && trusted;
    let (snapshot, count) = on_main(app, move || write(&text, restore)).await?;
    if !trusted {
        return Err("没有辅助功能权限，文字已复制到剪贴板".into());
    }
    post_paste();
    if let Some(snapshot) = snapshot {
        let app = app.clone();
        tauri::async_runtime::spawn(async move {
            tokio::time::sleep(RESTORE_AFTER).await;
            if let Err(e) = on_main(&app, move || restore_if_unchanged(snapshot, count)).await {
                log::warn!("could not restore the clipboard: {e}");
            }
        });
    }
    Ok(())
}

async fn on_main<R: Runtime, T: Send + 'static>(
    app: &AppHandle<R>,
    f: impl FnOnce() -> T + Send + 'static,
) -> Result<T, String> {
    let (tx, rx) = tokio::sync::oneshot::channel();
    app.run_on_main_thread(move || {
        let _ = tx.send(f());
    })
    .map_err(|e| e.to_string())?;
    rx.await
        .map_err(|_| "main thread dropped the task".to_string())
}

fn write(text: &str, conceal: bool) -> (Option<Snapshot>, isize) {
    let pb = NSPasteboard::generalPasteboard();
    let snapshot = conceal.then(|| snapshot(&pb));
    pb.clearContents();
    let item = NSPasteboardItem::new();
    item.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString });
    if conceal {
        let empty = NSData::new();
        for t in MARKER_TYPES {
            item.setData_forType(&empty, &NSString::from_str(t));
        }
    }
    write_items(&pb, vec![item]);
    (snapshot, pb.changeCount())
}

fn snapshot(pb: &NSPasteboard) -> Snapshot {
    let Some(items) = pb.pasteboardItems() else {
        return Vec::new();
    };
    items
        .iter()
        .map(|item| {
            item.types()
                .iter()
                .filter_map(|t| item.dataForType(&t).map(|d| (t.to_string(), d.to_vec())))
                .collect()
        })
        .collect()
}

fn restore_if_unchanged(snapshot: Snapshot, count: isize) {
    let pb = NSPasteboard::generalPasteboard();
    if pb.changeCount() != count {
        log::info!("clipboard changed since pasting; not restoring it");
        return;
    }
    pb.clearContents();
    let items = snapshot
        .iter()
        .map(|entries| {
            let item = NSPasteboardItem::new();
            for (t, data) in entries {
                item.setData_forType(&NSData::with_bytes(data), &NSString::from_str(t));
            }
            item
        })
        .collect();
    write_items(&pb, items);
}

fn write_items(pb: &NSPasteboard, items: Vec<Retained<NSPasteboardItem>>) {
    if items.is_empty() {
        return;
    }
    let objects: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = items
        .into_iter()
        .map(ProtocolObject::from_retained)
        .collect();
    if !pb.writeObjects(&NSArray::from_retained_slice(&objects)) {
        log::warn!("pasteboard refused the items");
    }
}

fn post_paste() {
    unsafe {
        let source = CGEventSourceCreate(kCGEventSourceStateCombinedSessionState);
        for down in [true, false] {
            let event = CGEventCreateKeyboardEvent(source, KEY_V, down);
            if event.is_null() {
                continue;
            }
            // Explicit flags, so modifiers still held physically do not leak in.
            CGEventSetFlags(event, kCGEventFlagMaskCommand);
            CGEventSetIntegerValueField(event, kCGEventSourceUserData, INJECTED);
            CGEventPost(kCGHIDEventTap, event);
            CFRelease(event);
        }
        if !source.is_null() {
            CFRelease(source);
        }
    }
}
